services:
  - type: web
    name: jobease
    runtime: image
    repo: https://github.com/sherwin-cell/jobease
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:azn4cnqBxJw0Er2NHEIrkvjLijypklPplS1xEtOEs9w=
      - key: DB_CONNECTION
        value: sqlite
      - key: PORT
        value: 10000
    dockerCommand: php artisan serve --host=0.0.0.0 --port=10000